name: NPM Publish on Release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Authenticate with Verdaccio
        run: npm config set 'http://18.195.169.73:4873/:_authToken' 'CVWjjCu6WyjhEd+si2puYA=='

      - name: Publish to Verdaccio
        run: npm publish
